let cameraStream=null;let selectedImages=[];let lastScanResult=null;let currentUser=null;let cachedScans=[];
const $=(id)=>document.getElementById(id);const loginScreen=$('loginScreen'),appShell=$('appShell'),loginForm=$('loginForm'),signupForm=$('signupForm');
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function showModal(id){$(id).classList.remove('hidden')}function closeModal(id){$(id).classList.add('hidden')}
function initials(name='User'){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}
function showApp(user){currentUser=user;loginScreen.classList.add('hidden');appShell.classList.remove('hidden');$('userName').textContent=user.username;$('userAvatar').textContent=initials(user.username);$('userRole').textContent=user.role==='admin'?'Administrator':'Authorized user';if(user.role==='admin')$('adminButton').classList.remove('hidden');switchSection('home');loadDashboard()}
async function api(url,opts={}){const r=await fetch(url,opts);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Something went wrong.');return d}
async function checkSession(){try{const d=await api('/api/auth/me');showApp(d.user)}catch{loginScreen.classList.remove('hidden');appShell.classList.add('hidden')}}
loginForm.addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const d=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:loginForm.username.value.trim(),password:loginForm.password.value})});loginForm.reset();showApp(d.user)}catch(err){$('loginError').textContent=err.message}});
$('showSignupButton').addEventListener('click',()=>{loginForm.classList.add('hidden');signupForm.classList.remove('hidden');$('signupError').textContent=''});$('showLoginButton').addEventListener('click',()=>{signupForm.classList.add('hidden');loginForm.classList.remove('hidden');$('loginError').textContent=''});
signupForm.addEventListener('submit',async e=>{e.preventDefault();$('signupError').textContent='';if(signupForm.password.value!==signupForm.passwordConfirmation.value){$('signupError').textContent='Passwords do not match.';return}try{const d=await api('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:signupForm.username.value.trim(),password:signupForm.password.value})});signupForm.reset();showApp(d.user)}catch(err){$('signupError').textContent=err.message}});
$('logoutButton').addEventListener('click',async()=>{await fetch('/api/auth/logout',{method:'POST'});if(cameraStream)stopCamera();appShell.classList.add('hidden');loginScreen.classList.remove('hidden')});
function switchSection(id){document.querySelectorAll('.page-section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===id));const meta={home:['WELCOME','What would you like to do?','Choose one option. You don\'t need to know how the system works.'],scan:['INSPECTION','Check a package','Capture the label first. Product details are optional and are not required.'],records:['RECORDS','Inspection history','Previous checks are kept here so they never get in the way of a new inspection.']};$('pageEyebrow').textContent=meta[id][0];$('pageTitle').textContent=meta[id][1];$('pageSubtitle').textContent=meta[id][2];if(id==='records')loadHistory();$('sidebar').classList.remove('open')}
document.querySelectorAll('.nav-item,[data-section-target]').forEach(el=>el.addEventListener('click',()=>switchSection(el.dataset.sectionTarget||el.dataset.section)));
$('guideButton').addEventListener('click',()=>showModal('guideModal'));$('adminButton').addEventListener('click',()=>{showModal('adminModal');loadAdminUsers()});$('mobileMenuButton').addEventListener('click',()=>$('sidebar').classList.toggle('open'));document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.closeModal)));document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
function generateId(){return `LOCAL-${Date.now().toString(36).toUpperCase()}`}
function showSelectedImages(files){selectedImages=Array.from(files).slice(0,3);if(!selectedImages.length)return;$('imagePreview').src=URL.createObjectURL(selectedImages[0]);$('imagePreview').classList.remove('hidden');$('cameraPreview').classList.add('hidden');$('scannerPlaceholder').classList.add('hidden');$('cameraMessage').textContent=`${selectedImages.length} photo${selectedImages.length>1?'s':''} selected. Ready to check.`;$('cameraStatus').textContent='Photo selected';$('captureStage').scrollIntoView({behavior:'smooth',block:'start'})}
$('imageInput').addEventListener('change',()=>showSelectedImages($('imageInput').files));
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){$('cameraMessage').textContent='Camera is not supported in this browser. Upload a photo instead.';return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('cameraPreview').srcObject=cameraStream;$('cameraPreview').classList.remove('hidden');$('imagePreview').classList.add('hidden');$('scannerPlaceholder').classList.add('hidden');$('startCameraButton').classList.add('hidden');$('captureButton').classList.remove('hidden');$('stopCameraButton').classList.remove('hidden');$('cameraStatus').textContent='Camera active';$('cameraMessage').textContent='Move the package until the label is clear, then take a photo.'}catch(err){$('cameraMessage').textContent='Camera access was blocked. You can upload a photo instead.'}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}$('cameraPreview').srcObject=null;$('cameraPreview').classList.add('hidden');$('startCameraButton').classList.remove('hidden');$('captureButton').classList.add('hidden');$('stopCameraButton').classList.add('hidden');$('cameraStatus').textContent='Camera ready'}
$('startCameraButton').addEventListener('click',startCamera);$('stopCameraButton').addEventListener('click',stopCamera);$('captureButton').addEventListener('click',()=>{if(!cameraStream)return;const v=$('cameraPreview'),c=$('captureCanvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);c.toBlob(blob=>{const f=new File([blob],`package-${Date.now()}.jpg`,{type:'image/jpeg'});selectedImages=[f];$('imagePreview').src=URL.createObjectURL(f);$('imagePreview').classList.remove('hidden');$('cameraPreview').classList.add('hidden');$('cameraMessage').textContent='Photo captured. You can check it now.';$('cameraStatus').textContent='Photo captured';stopCamera()},'image/jpeg',.92)});
function clearInspection(){selectedImages=[];lastScanResult=null;$('imageInput').value='';$('imagePreview').classList.add('hidden');$('scannerPlaceholder').classList.remove('hidden');$('cameraMessage').textContent='You can use one to three photos. The system will treat them as one inspection.';$('error').textContent='';$('resultSection').classList.add('hidden');$('loadingPanel').classList.add('hidden');$('cameraStatus').textContent='Camera ready';$('issuesSummary').innerHTML='';if(cameraStream)stopCamera()}
$('newScanButton').addEventListener('click',()=>{clearInspection();switchSection('scan');window.scrollTo({top:0,behavior:'smooth'})});
async function analyzeImage(){if(!selectedImages.length){$('error').textContent='Please take a photo or upload a package image first.';toast('Photo required');return}const fd=new FormData();selectedImages.forEach(i=>fd.append('images',i));$('loadingPanel').classList.remove('hidden');$('scanButton').disabled=true;$('error').textContent='';try{const d=await fetch('/scan',{method:'POST',body:fd});const data=await d.json();if(!d.ok)throw new Error(data.error||'Inspection failed.');lastScanResult=data;displayResult(data);$('resultSection').classList.remove('hidden');$('resultSection').scrollIntoView({behavior:'smooth'});await loadDashboard();toast('Inspection complete')}catch(err){$('error').textContent=err.message;toast('Inspection could not be completed')}finally{$('loadingPanel').classList.add('hidden');$('scanButton').disabled=false}}
$('scanButton').addEventListener('click',analyzeImage);
function normalizeStatus(s){return s==='NON-COMPLIANT'?'Issues found':s==='COMPLIANT'?'Compliant':'Needs review'}function statusClass(s){return s==='COMPLIANT'?'pass':s==='NON-COMPLIANT'?'fail':'review'}
function displayResult(data){const c=data.compliance||{},r=data.readability||{};const status=c.overall_status||'NEEDS REVIEW';$('overallStatus').textContent=normalizeStatus(status);$('resultHeadline').textContent=status==='COMPLIANT'?'Package appears compliant':status==='NON-COMPLIANT'?'Issues were found':'Manual review recommended';$('statusDescription').textContent=status==='COMPLIANT'?'The available checks passed based on the information detected from the label.':status==='NON-COMPLIANT'?'Some required information or checks did not pass. Review the highlighted items.':'The system could not confidently confirm every check. A person should review the highlighted items.';$('resultIcon').textContent=status==='COMPLIANT'?'✓':status==='NON-COMPLIANT'?'!':'?';$('complianceScore').textContent=`${c.score||0}%`;$('scoreProgress').style.width=`${Math.max(0,Math.min(100,Number(c.score||0)))}%`;$('passedCount').textContent=c.passed||0;$('manualCount').textContent=c.manual_review||0;$('readabilityStatus').textContent=r.status||'UNKNOWN';const conf=Number(r.average_confidence||0);$('readabilityConfidence').textContent=`${Math.round(conf)}%`;$('ocrProgress').style.width=`${Math.max(0,Math.min(100,conf))}%`;$('ocrText').textContent=data.extracted_text||'No text detected.';renderDeclarations(data.text_data||[]);renderRules(c.results||[]);renderIssues(c.results||[]);$('resultBanner').className=`result-banner status-${statusClass(status)}`}
function renderDeclarations(items){const el=$('declarationsList');el.innerHTML='';if(!items.length){el.innerHTML='<div class="empty-state"><div>⌕</div><strong>No usable declarations detected</strong><p>The label may need a clearer photo.</p></div>';return}items.slice(0,20).forEach(x=>{el.insertAdjacentHTML('beforeend',`<div class="declaration-item"><div><span>Detected text</span><strong>${esc(x.text)}</strong></div><div><span>Confidence</span><strong>${Math.round(x.confidence||0)}%</strong></div></div>`)})}
function renderRules(items){const body=$('ruleTableBody');body.innerHTML='';if(!items.length){body.innerHTML='<tr><td colspan="3">No rule results available.</td></tr>';return}items.forEach(x=>body.insertAdjacentHTML('beforeend',`<tr><td><strong>${esc(x.field||'Requirement')}</strong></td><td>${esc(x.description||'')}</td><td><span class="badge ${statusClass(x.status==='PASS'?'COMPLIANT':x.status==='FAIL'?'NON-COMPLIANT':'NEEDS REVIEW')}">${esc(x.status||'REVIEW')}</span></td></tr>`))}
function renderIssues(items){const issues=items.filter(x=>x.status==='FAIL'||x.status==='MANUAL REVIEW');const el=$('issuesSummary');if(!issues.length){el.innerHTML='<div class="issue-card"><div class="issue-dot">✓</div><div><h4>No issues detected in the evaluated checks</h4><p>The available automated checks passed.</p></div></div>';return}el.innerHTML=issues.map(x=>`<div class="issue-card ${x.status==='FAIL'?'fail':''}"><div class="issue-dot">${x.status==='FAIL'?'!':'?'}</div><div><h4>${esc(x.field||'Review item')}</h4><p>${esc(x.description||'This item needs attention.')}</p></div><span class="badge ${x.status==='FAIL'?'fail':'review'}">${esc(x.status)}</span></div>`).join('');}
async function loadDashboard(){try{const d=await api('/api/scans');cachedScans=d.scans||[];const s=cachedScans; $('totalScans').textContent=s.length;$('compliantScans').textContent=s.filter(x=>x.overall_status==='COMPLIANT').length;$('failedScans').textContent=s.filter(x=>x.overall_status==='NON-COMPLIANT').length;$('reviewScans').textContent=s.filter(x=>!['COMPLIANT','NON-COMPLIANT'].includes(x.overall_status)).length}catch{}}
async function loadHistory(){try{if(!cachedScans.length){const d=await api('/api/scans');cachedScans=d.scans||[]}renderHistory()}catch{$('historyTableBody').innerHTML='<tr><td colspan="5">Unable to load records.</td></tr>'}}
function renderHistory(){const q=$('historySearch').value.trim().toLowerCase(),f=$('historyFilter').value;const rows=cachedScans.filter(x=>(`${x.scan_id||''} ${x.overall_status||''}`.toLowerCase().includes(q))&&(f==='all'||x.overall_status===f));const body=$('historyTableBody');body.innerHTML='';$('historyEmpty').classList.toggle('hidden',rows.length!==0);rows.forEach(x=>body.insertAdjacentHTML('beforeend',`<tr><td><strong>${esc(x.scan_id)}</strong><div class="muted-line">${esc(x.product_name||'Package inspection')}</div></td><td><span class="badge ${statusClass(x.overall_status)}">${normalizeStatus(x.overall_status)}</span></td><td>${Number(x.compliance_score||0)}%</td><td>${formatDate(x.created_at)}</td><td><button class="link-button view-row" data-id="${esc(x.scan_id)}">View</button></td></tr>`));document.querySelectorAll('.view-row').forEach(b=>b.addEventListener('click',()=>viewScan(b.dataset.id)))}
$('historySearch').addEventListener('input',renderHistory);$('historyFilter').addEventListener('change',renderHistory);
function formatDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
async function viewScan(id){try{const d=await api(`/api/scans/${encodeURIComponent(id)}`),s=d.scan,issues=d.violations||[];$('detailTitle').textContent=s.scan_id;$('scanDetailContent').innerHTML=`<div class="scan-detail"><div><span>Status</span><strong>${normalizeStatus(s.overall_status)}</strong></div><div><span>Score</span><strong>${Number(s.compliance_score||0)}%</strong></div><div><span>Date</span><strong>${formatDate(s.created_at)}</strong></div><div><span>Readability</span><strong>${esc(s.readability_status||'—')}</strong></div></div><div class="panel" style="margin-top:14px"><div class="panel-title"><h3>Review items</h3></div>${issues.length?issues.map(i=>`<div class="issue-card ${i.status==='FAIL'?'fail':''}"><div class="issue-dot">${i.status==='FAIL'?'!':'?'}</div><div><h4>${esc(i.field||i.rule_id)}</h4><p>${esc(i.description||'')}</p></div><span class="badge ${i.status==='FAIL'?'fail':'review'}">${esc(i.status)}</span></div>`).join(''):'<div class="issue-card"><div class="issue-dot">✓</div><div><h4>No saved violations</h4></div></div>'}</div><div class="result-actions"><button class="button primary" id="detailPdf">PDF report</button><button class="button ghost" id="detailWord">Word report</button></div>`;$('detailPdf').onclick=()=>generateReportForScan(s,'/api/reports/pdf','compliance-report.pdf');$('detailWord').onclick=()=>generateReportForScan(s,'/api/reports/word','compliance-report.docx');showModal('scanDetailModal')}catch(err){toast(err.message)}}
async function generateReportForScan(s,endpoint,filename){try{const d=await api(`/api/scans/${encodeURIComponent(s.scan_id)}`);const payload={scan_id:s.scan_id,product_name:s.product_name,product_type:s.product_type,package_type:s.package_type,extracted_text:s.extracted_text,readability:{status:s.readability_status,average_confidence:s.readability_confidence},compliance:{overall_status:s.overall_status,score:s.compliance_score}};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){let e={};try{e=await r.json()}catch{}throw new Error(e.error||'Report generation failed.')}const blob=await r.blob();const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename;a.click();URL.revokeObjectURL(u);toast('Report downloaded')}catch(err){toast(err.message)}}
$('pdfButton').addEventListener('click',()=>lastScanResult&&generateReportForScan({scan_id:lastScanResult.scan_id,product_name:lastScanResult.product_name,product_type:lastScanResult.product_type,package_type:lastScanResult.package_type,extracted_text:lastScanResult.extracted_text,readability:lastScanResult.readability,overall_status:lastScanResult.compliance?.overall_status,compliance_score:lastScanResult.compliance?.score},'/api/reports/pdf','compliance-report.pdf'));$('wordButton').addEventListener('click',()=>lastScanResult&&generateReportForScan({scan_id:lastScanResult.scan_id,product_name:lastScanResult.product_name,product_type:lastScanResult.product_type,package_type:lastScanResult.package_type,extracted_text:lastScanResult.extracted_text,readability:lastScanResult.readability,overall_status:lastScanResult.compliance?.overall_status,compliance_score:lastScanResult.compliance?.score},'/api/reports/word','compliance-report.docx'));
async function loadAdminUsers(){try{const d=await api('/api/admin/users');$('adminUsers').innerHTML=(d.users||[]).map(u=>`<div class="admin-user-row"><div><strong>${esc(u.username)}</strong><small>${esc(u.role)} · created ${formatDate(u.created_at)}</small></div><button class="status-toggle ${u.active?'active':'inactive'}" data-user-id="${u.id}" data-active="${u.active}">${u.active?'Active':'Inactive'}</button></div>`).join('')||'<div class="empty-state"><strong>No users</strong></div>';document.querySelectorAll('.status-toggle').forEach(b=>b.addEventListener('click',()=>toggleUser(b.dataset.userId,b.dataset.active==='1'||b.dataset.active==='true')))}catch(err){$('adminUsers').innerHTML=`<div class="form-error">${esc(err.message)}</div>`}}
async function toggleUser(id,active){const endpoint=active?`/api/admin/users/${id}/deactivate`:`/api/admin/users/${id}/activate`;try{await api(endpoint,{method:'POST'});loadAdminUsers();toast('User status updated')}catch(err){toast(err.message)}}
$('adminCreateForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('adminUsername').value.trim(),password:$('adminPassword').value,role:$('adminRole').value})});e.target.reset();loadAdminUsers();toast('User added')}catch(err){toast(err.message)}});
$('adminHealthButton').addEventListener('click',async()=>{try{const d=await api('/api/health');toast(d.message||'System online')}catch{toast('System health check failed')}});
window.addEventListener('beforeunload',()=>{if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop())});checkSession();
